server:
  port: 8080
  undertow:
    threads:
      io: 4
      worker: 200

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:
    tags:
      application: bff-blocking
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.wagnercaetano: INFO
