server:
  port: 8080

spring:
  codec:
    max-in-memory-size: 1MB

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:
    tags:
      application: bff-reactive
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
      sla:
        http.server.requests: 50ms,100ms,150ms,200ms,300ms,500ms,1000ms
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.wagnercaetano: INFO
